### ISSUE TITLE
退出时段错误

### ISSUE THREAD

**Issue by Ryan-Git** [brpc/braft#142]
堆栈如下
```
Program received signal SIGSEGV, Segmentation fault.
#0  0x00007ffff63615db in malloc_consolidate () from /lib64/libc.so.6
#1  0x00007ffff63624fe in _int_free () from /lib64/libc.so.6
#2  0x0000000000edade9 in butil::FlatMap<unsigned long, brpc::ConnectStatistics, butil::DefaultHasher<unsigned long>, butil::DefaultEqualTo<unsigned long>, false>::~FlatMap (this=0x25b2a60, __in_chrg=<optimized out>)
    at /home/renhongdi02/blade-kv/deps/brpc/src/butil/containers/flat_map_inl.h:237
#3  0x0000000000edaa66 in brpc::Acceptor::~Acceptor (this=0x25b2990, __in_chrg=<optimized out>) at /home/renhongdi02/blade-kv/deps/brpc/src/brpc/acceptor.cpp:42
#4  0x0000000000edaaf1 in brpc::Acceptor::~Acceptor (this=0x25b2990, __in_chrg=<optimized out>) at /home/renhongdi02/blade-kv/deps/brpc/src/brpc/acceptor.cpp:45
#5  0x0000000000e137e4 in brpc::Server::~Server (this=0x2a94a00, __in_chrg=<optimized out>) at /home/renhongdi02/blade-kv/deps/brpc/src/brpc/server.cpp:417
```
Acceptor 的 socket map 如下
```
p _socket_map
$2 = {_size = 0, _nbucket = 65536, _buckets = 0x2758c20, _thumbnail = 0x0, _load_factor = 80, _hashfn = {<__gnu_cxx::hash<unsigned long>> = {<No data fields>}, <No data fields>},
  _eql = {<std::equal_to<unsigned long>> = {<std::binary_function<unsigned long, unsigned long, bool>> = {<No data fields>}, <No data fields>}, <No data fields>}, _pool = {static BLOCK_SIZE = <optimized out>,
    static NITEM = <optimized out>, static ITEM_SIZE = <optimized out>, _free_nodes = 0x0, _blocks = 0x0}}
```

可能是什么原因？
使用上我们在一个进程里开了三副本，每个副本一个独立的端口。在退出时偶尔会发生这个错误。

**Comment by PFZheng** [comment]
可以联编 ASAN 看看，Segmentation fault 很多发生的时候不是第一现场

**Comment by PFZheng** [comment]
另外确认下是不是没有优雅退出，譬如说没有调用RunUntilAskedToQuit

**Comment by Ryan-Git** [comment]
看代码析构时候就调了 stop 和 join 啊。valgrind 没测出什么问题。
server 是个成员，改成非指针似乎就好了，不知道为什么。。

**Comment by PFZheng** [comment]
> 看代码析构时候就调了 stop 和 join。valgrind 没测出什么问题。
> server 是个成员，改成非指针似乎就好了，不知道为什么。。

听起来还是server生命周期的问题

**Comment by Ryan-Git** [comment]
恩，先关了，有进一步发现再开吧。感谢支持。

**Comment by Ryan-Git** [comment]
假象，又出现了。
ASAN 也没测出问题。。。
